<a href="https://colab.research.google.com/github/pankajkumarpmp/AI-ML/blob/main/synonyms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Define a list of words and their synonyms
words_and_synonyms = [
    {'word': 'happy', 'synonyms': ['joyful', 'content', 'pleased']},
    {'word': 'sad', 'synonyms': ['unhappy', 'depressed', 'gloomy']},
    {'word': 'angry', 'synonyms': ['irritated', 'enraged', 'furious']},
    # Add more words and synonyms as needed
]

# Convert the list of words and synonyms into a single list of words
words = []
for item in words_and_synonyms:
    word = item['word']
    synonyms = item['synonyms']
    words.append(word)
    words.extend(synonyms)

# Use CountVectorizer to convert the words into numerical representations
vectorizer = CountVectorizer().fit_transform(words)

# Print the numerical representations of the words
print(vectorizer.toarray())



[[0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]]


In [41]:
# Convert the list of words and synonyms into a single list of words
words = []
for item in words_and_synonyms:
    word = item['word']
    synonyms = item['synonyms']
    words.append(word)
    words.extend(synonyms)

# Use CountVectorizer to convert the words into numerical representations
vectorizer = CountVectorizer().fit_transform(words)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(vectorizer.toarray(), words, test_size=0.2)

# Print the shapes of the training and testing sets
print(X_train.shape)
print(X_test.shape)

(9, 12)
(3, 12)


In [48]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)

KNeighborsClassifier()

In [52]:
# Evaluate the model on the testing data
predictions = model.predict(X_test)
accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions,  average='micro')
recall = recall_score(y_test, predictions,  average='micro')
f1 = f1_score(y_test, predictions, average='micro')


In [53]:
# Print the results
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Accuracy: 0.0
Precision: 0.0
Recall: 0.0
F1 Score: 0.0


In [55]:
# Fine-tune the model if performance is not satisfactory
if accuracy < 0.8 or precision < 0.8 or recall < 0.8 or f1 < 0.8:
    # Try adjusting model parameters
    model = KNeighborsClassifier(n_neighbors=3)
    model.fit(X_train, y_train)

In [57]:
    # Re-evaluate the model on the testing data
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions,  average='micro')
    recall = recall_score(y_test, predictions,  average='micro')
    f1 = f1_score(y_test, predictions, average='micro')

In [62]:
    # Try changing the type of model if performance is still not satisfactory
    if accuracy < 0.8 or precision < 0.8 or recall < 0.8 or f1 < 0.8:
        from sklearn.tree import DecisionTreeClassifier

        model = DecisionTreeClassifier()
        model.fit(X_train, y_train)

        # Re-evaluate the model on the testing data
        predictions = model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        precision = precision_score(y_test, predictions, average='micro')
        recall = recall_score(y_test, predictions , average='micro')
        f1 = f1_score(y_test, predictions, average='micro')

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", f1)

Accuracy:  0.0
Precision:  0.0
Recall:  0.0
F1 Score:  0.0


In [66]:
# Input a word for which you want to find synonyms
input_word = input("Enter a word: ")
input_word = [input_word]
# Convert the input word into a numerical representation
input_vector = CountVectorizer().fit_transform(words)

#X_train, X_test, y_train, y_test = train_test_split(vectorizer.toarray(), words, test_size=0.2)

# Use the fine-tuned model to make predictions
predictions = model.predict(input_vector)

# Convert the predictions back to words
predicted_synonyms = tf.keras.preprocessing.text.Tokenizer().fit_on_texts(predictions)

# Print the predicted synonyms
print("The predicted synonyms for the word '{}' are: {}".format(input_word, predicted_synonyms))


Enter a word: happy
The predicted synonyms for the word '['happy']' are: None
